node_js: 
  - "9",
language:  
  - "node_js"
services: 
  - "postgresql"

before_script:
  - psql -c 'create database codesling;' -U postgres
  - yarn buildEnv
  - yarn setup
  - createuser root
  - yarn db:setup:rest-server
  - yarn start &
  - sleep 10 